[package]
name = "thouart"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2"
regex = "1"
thiserror = "1"
tokio = { version = "1", features = ["io-std", "io-util", "macros", "rt", "sync"] }
