[package]
name = "thouart"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.32"
libc = "0.2.186"
regex = "1.12.3"
term = "1.2.1"
termini = "1.0.0"
thiserror = "2.0.18"
tokio = { version = "1.52.3", features = ["io-std", "io-util", "macros", "rt", "rt-multi-thread", "signal", "sync", "time"] }
tokio-tungstenite = "0.29.0"

[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3.9", features = ["consoleapi", "namedpipeapi", "processenv", "wincon", "winnt"] }

[dev-dependencies]
portable-pty = "0.9.0"
