name: Test
on: [ push ]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-12]
    steps:
    - name: Checkout
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
    - name: Format
      run: cargo fmt -- --check
    - name: Lint
      run: cargo clippy -- --no-deps
    - name: Build
      run: cargo build
    - name: Test
      run: cargo test
